# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_website',
                'doc_host': 'https://HafizAhmadHassan.github.io',
                'git_url': 'https://github.com/HafizAhmadHassan/my_website',
                'lib_path': 'my_website'},
  'syms': {'my_website.core': {'my_website.core.foo': ('core.html#foo', 'my_website/core.py')}}}